#!/usr/bin/env php
<?php

declare(strict_types=1);

$autoloadPath = __DIR__ . '/../vendor/autoload.php';

if (!file_exists($autoloadPath)) {
    fwrite(STDERR, "Error: Composer autoload not found. Please run 'composer install'.\n");
    exit(1);
}

require_once $autoloadPath;

use Symfony\Component\Console\Application;
use Vix\ExceptionInspector\Command\AnalyzeCommand;

$application = new Application('PHP Exception Inspector', '0.1.9');
$application->add(new AnalyzeCommand());
$application->setDefaultCommand('analyze', true);

$application->run();
